# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EcoHealth Alliance
email: homeoffice@ecohealthalliance.org
predict-email: PREDICTmodeling@ecohealthalliance.org
description: > # this means to ignore newlines until "baseurl:"
  Live Science is EcoHealth Alliance's home for in-progress
  analyses and scientific reports.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://livescience.ecohealthalliance.org" # the base hostname & protocol for your site
twitter_username: EcoHealthNYC

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - TODO.md
  - .Rproj.user
  - .Rhistory
  - ma-site.Rproj

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
